### ISSUE TITLE
Query regarding generators used.

### ISSUE THREAD

**Issue by kadarsh22** [chail/gan-ensembling#2]
Hi. Congratulations on this novel work. I had a query when going through the code, when loading the stylegan2 generator with dataset name  "Celebahq", a print statement is shown saying "Mapping Celebahq dataset (with labels) to FFHQ generators (unlabeled)" and the generator being downloaded is of FFHQ. Could you clarify why is this being done? Also, are you using Celebahq or FFHQ(confused because of the above code snippet)? Also when I load the latents from latents.zip from celeba hq and feed it to stylegan generator model, the image generated is very different from the actual image from Celeba Dataset

**Comment by chail** [comment]
We are using the pretrained FFHQ face generator for StyleGAN2 as the generic face image prior. But since this is doing a labelled classification task, we need a dataset with labels so we are using the labels from CelebAHQ for the task. FFHQ is more diverse than CelebAHQ, so we find that the FFHQ generator can encode faces from CelebAHQ reasonably well. 

Note that CelebA and CelebAHQ is not the same -- CelebAHQ is a subset of CelebA, and the face alignment is slightly different. In latents.zip the individual latents are named with a number, e.g. `000009.pth`; this corresponds to the image `000009.jpg` in CelebA following the CelebAHQ alignment. The following is an example of the `000009` image from CelebAHQ and corresponding generation from the the latent code. 

![image](https://user-images.githubusercontent.com/9330220/150229192-814eb9a8-b32b-4d80-9e73-00645b72b4a8.png)

**Comment by kadarsh22** [comment]
Thank you. That cleared my doubt.
